
#########################################################################################
#                                                                                       #
# SwiftLint configuration file.                                                         #
#                                                                                       #
# To get an overview of all configuration possibilities check:                          #
# https://github.com/realm/SwiftLint                                                    #
#                                                                                       #
# To check the project's config it might be easier to use '$swiftlint rules'            #
# inside the projects directory instead of trying to parse this file with brainpower.   #
#                                                                                       #
#########################################################################################

#########################################################################################
# How to use: by adding a new run script in the project target build phase.             #
#                                                                                       #
#  ```                                                                                  #
#   "${PODS_ROOT}/SwiftLint/swiftlint"                                                  #
#  ```                                                                                  #
#  or                                                                                   #
# $SRCROOT/BuildPhasesScripts/SwiftLintRunScript.sh                                     #                                          #
#########################################################################################

#########################################################################################
# How to disable swiftlint check in code inline!                                        #
#                                                                                       #
#  ```                                                                                  #
#    //swiftlint:disable:next <rule name>                                               #                                             #
#  ```                                                                                  #                                        #
#########################################################################################

# We don't want to use swiftlint for our external dependencies.
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
    #- <ProjectDirectoryName>/<folder>
    #- <ProjectDirectoryName>/<folder>/<file>.<ext>

disabled_rules: # rule identifiers to exclude from running
#  - vertical_whitespace
#  - unused_closure_parameter
#  - shorthand_operator
#  - line_length
#  - large_tuple
#  - identifier_name
#  - control_statement
    - file_length
    - trailing_whitespace
    - comment_spacing
    - switch_case_alignment

opt_in_rules: # some rules are only opt-in
    - empty_count
    - missing_docs
    - force_unwrapping
    - closure_spacing
    - unused_import

# Limit line length to '220' characters.
# We need to specify both to avoid warnings at 120. (Default value) >> 100 for warning, 200 for error
line_length:
    warning: 120
    error: 220

# Force unwrapping should be avoided like the plague.
force_unwrapping: warning # or keep it as error if you prefer strict enforcement

# Even so they might seem to be not that important we want a clean code base right from the beginning.
# And even more important for the lazy one's: This will avoid superfluous style discussions and comments in PR's.
trailing_newline: error
trailing_semicolon: error
trailing_whitespace:
    severity: error
    ignores_empty_lines: true # or keep it as false if you prefer strict enforcement

custom_rules:
    # To avoid visual noise we eschew the auto-generated Xcode template documentation.
#    xcode_template_documentation:
#        match_kinds:
#            - comment
#        message: "No need for the xcode template documentation. Please remove it!"
#        regex: '^\/{2}\n\/{2}\s{2}[A-z]*.swift\n\/{2}\s*[A-z]*\n\/{2}\n\/{2}\s{2}Created'
#        severity: error
    rule_id:
        # included: Source/YourProject/Rules/\w+\.swift # Adjust this path to your project's structure
        name: "Rule ID"
        message: Rule IDs must be all lowercase, snake case and not end with `rule`
        #regex: identifier:\s*("\w+_rule"|"\S*[^a-z_]\S*")
        regex: ^\s*identifier:\s*"\w+"$
        severity: error

#identifier_name:
#    min_length: 2 # only warning
#    max_length: 30 # warning and error
#    warning: 20
#    error: 30
#    excluded: # excluded via string array
#    - id
#    - URL
#    - GlobalAPIKey
#    - by
#    - vc
#    - en
#    - ar
#    - to
#    - ad
    
identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - by
    - vc
    - en
    - ar
    - to
    - ad
    
type_name:
  min_length: 2 # only warning
  max_length: 30 # warning and error
  excluded:
    - iStarWarsUITests
    - iStarWarsTests
    
force_cast: warning # implicitly

force_try:
    severity: warning # explicitly

# they can set both implicitly with an array
type_body_length:
    - 200 # warning
    - 300 # error

file_length:
    warning: 500
    error: 800

file_name:
    excluded:
    - main.swift
    #- <iGeneratedFile.swift> # Add other files as needed
        
nesting:
  type_level:
    warning: 3 # warning appears if you nest 3 levels deep
    error: 6
